"""add adddress1 to user

Revision ID: be4d09b17ce2
Revises: 47f6f53a84cb
Create Date: 2026-03-12 08:35:51.300812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4d09b17ce2'
down_revision = '47f6f53a84cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address1', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address1')

    # ### end Alembic commands ###
